version: '3.9'

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "1"

x-openvpn: &openvpn
  image: josearodrigueze/vpn-multiclient
  <<: *logging # calling var &logging
  restart: unless-stopped
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  dns:
    - 1.1.1.1

services:
  vpn_1:
    <<: *openvpn # calling var &openvpn
    env_file:
      - .env.example
    environment:
      #- OVPN_FILE=co-bog.prod.surfshark.com_udp.ovpn
      #- SERVER_COUNTRY=CO
      - SERVER_CITY=Bog
    ports:
      - 127.0.0.1:8118:8118

