version: '3.9'

x-deploy: &deploy
  deploy:
    resources:
      limits:
        cpus: '0.1'
        memory: 50M

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "1"

x-openvpn: &openvpn
  image: josearodrigueze/vpn-multiclient
  <<: *logging # calling var &logging
  restart: unless-stopped
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  dns:
    - 1.1.1.1
  env_file:
    - .env # with this file config your environment var

services:
  openvpn_1:
    <<: *openvpn # calling var &openvpn
    container_name: openvpn_1

  test:
    image: byrnedo/alpine-curl
    container_name: test
    command: -s -L 'https://checkip.amazonaws.com'
    depends_on:
      openvpn_1:
        condition: service_healthy
    network_mode: service:openvpn_1
    restart: always

